const data={
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            slug:'nike-slim-shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price:1200,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:'10reviews',
            desciption:"High quality shirt",
        },
        {
            _id:'2',
            name:'Adidas Slim Shirt',
            slug:'adidas-slim-shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price:1250,
            countInStock:0,
            brand:'Adidas',
            rating:4.0,
            numReviews:'10reviews',
            desciption:'High quality shirt',
        },
        {
            _id:'3',
            name:'Nike Slim pant',
            slug:'nike-slim-pant',
            category: 'Pants',
            image: '/images/p3.jpg',
            price:1000,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:'10reviews',
            desciption:'High quality pants',
        },
        {
            _id:'4',
            name:'Adidas Baggy pant',
            slug:'adidas-Baggy-pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price:1100,
            countInStock:10,
            brand:'Adidas',
            rating:4.5,
            numReviews:10,
            desciption:'High quality pants',
        },
    ],
};
export default data;